security:
    role_hierarchy:
        ROLE_JUNIOR: ROLE_USER,
        ROLE_SENIOR: ROLE_JUNIOR
        ROLE_MENTOR: ROLE_SENIOR
        ROLE_TEAMLEAD: ROLE_MENTOR
        ROLE_SUPER_ADMIN: ROLE_TEAMLEAD
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern: ^/api                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false             